name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Обновлено до версии 3
        with:
          fetch-depth: 0  # Получаем полный репозиторий для корректной работы с тегами

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Обновлено до версии 3
        with:
          node-version: '18'  # Устанавливаем Node.js версии 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps # Устанавливаем зависимости

      - name: Configure Git
        run: |
          git config --global user.name "melnicenkovadik" # Твоё имя
          git config --global user.email "melnicenkovadik@gmail.com" # Твой email

      - name: Bump version
        id: bump_version
        run: |
          current_version=$(node -p "require('./package.json').version")
          echo "Current version: $current_version"
          npm version patch -m "chore: bump version to %s" # Увеличиваем версию пакета
          new_version=$(node -p "require('./package.json').version")
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV
          git status  # Проверка статуса после изменения

      - name: Build and extract types
        run: |
          npm run build
          npm run api-extractor # Выполняем api-extractor для генерации объединённого файла .d.ts

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/melnicenkovadik/customlibtest.git
          git add -f package.json package-lock.json dist/my-component-library.d.ts
          
          # Проверка наличия изменений перед коммитом
          if ! git diff --cached --quiet; then
            git commit -m "chore: bump version to ${{ env.new_version }}"
            git tag -a "v${{ env.new_version }}" -m "Release version ${{ env.new_version }}"
            git push origin main
            git push origin "v${{ env.new_version }}"  # Пушим также новый тег
          else
            echo "No changes to commit."
          fi
