name: Bump version and publish

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure Git
        run: |
          git config --global user.name "melnicenkovadik"
          git config --global user.email "melnicenkovadik@gmail.com"

      - name: Bump version
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          npm version patch -m "chore: bump version to %s"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/melnicenkovadik/customlibtest.git
          git push -f origin main --follow-tags

      - name: Fix npm package warnings
        run: npm pkg fix

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          npm publish
